### ISSUE TITLE
Service playbook fails on Stretch because of old repo URL

### ISSUE THREAD

**Issue by evilham** [debops/ansible-rstudio_server#3]
We should probably change the repo to be
`https://cran.rstudio.com/bin/linux/debian stretch-cran34`
as opposed to
`https://cran.rstudio.com/bin/linux/debian stretch-cran3`

This would work with jessie (old stable) as well but not with wheezy (old old stable).

**Comment by drybjed** [comment]
OK. That could be handled by a condition that checks if current OS release is `wheezy` and uses `cran3`, else uses `cran34`.

**Comment by evilham** [comment]
Probably better ^^. Right now I'm just testing a lot of different roles and documenting any issues I'm finding and how they might be solved.

To this issue, I must add that the signing key for the R repo changed as of April 2017:
https://cran.rstudio.com/bin/linux/debian/

**Comment by evilham** [comment]
Serious question: did this ever actually work? From what I gather, it tries to install only if `rstudio-server` and `libssl0.9.8` are available in `apt-cache`.

Turns out, `rstudio-sever` is not in cran's repositories (nor in debian's) and stretch has only `libssl1.02` and `libssl1.1`, where `jessie` has `libssl1.0.0`. On Ubuntu it's quite analogue respecting libssl's versions.

Would it be OK to install Rstudio-server (and later on Shiny-server) by passing the URL to the `deb` argument in ansible's [apt](http://docs.ansible.com/ansible/apt_module.html)
I'm not sure anymore, but I think the force flag has to be passed as well, because Rstudio depends hard on a specific version of libssl; it does work at least on jessie.

**Comment by drybjed** [comment]
I suppose it's time for some context. :-) Don't you think that `debops.rstudio_server` is a weird fit with the rest of the DebOps roles? I mean, lot's of Debian management, and then some weird R service... I don't use R personally, one of my university users requested the RStudio server deployment and I did it in Ansible. Since the role was already written, I just added it to DebOps. I guess it could fit in with the HPC angle I wish someday to explore, with SLURM, MPI and other such tools.

Anyway, the role was written when Debian Wheezy was Stable, I think just before the Jessie release. RStudio didn't provide a convenient APT repository, the `rstudio-server` package relied on old `libssl0.9.8` from Squeeze, and Ansible `apt` module didn't have the `deb` parameter, so I did what I thought was the least painful solution - I put the `rstudio-server` package on our local APT repository managed by `debops.reprepro` (I don't remember how I dealt with `libssl0.9.8` at the moment). The application was deployed on a last Debian Wheezy production machine I ever built and it sits there ever since. I just checked and this machine is still used to calculate something in R, right at this moment. I'm not sure if RStudio server is even used, I imagine that the one user that still logs in, uses shell and `screen` because there's no job scheduling. Hmm, mybe I should tell them about `at`, which is available there?

So, long story short, the service was deployed, worked, the users were happy. I explained the installation procedure [in the role documentation](https://docs.debops.org/en/latest/ansible/roles/ansible-rstudio_server/docs/getting-started.html) and that was it. Because the `rstudio-server` package was not in the default APT repositories, and depended on a package from a previous release, I added the checks for these packages in the role to not fail horribly when they were not available. Since then, DebOps got its own [Software Source Policy](https://docs.debops.org/en/latest/debops-policy/docs/software-source-policy.html) which I wrote partially based on my experiences with `rstudio-server` package. As I said before, I'm not an R user, so the role was unchanged from that time; you can tell by the `defaults/main.yml` file, lack of namespaced variables and use of `vars/main.yml`. Nobody asked me about it unitl you came along. :-)

Meanwhile, world moved on. RStudio released new version of the software, it should work on Jessie now, I wonder when they release a version for Stretch. And they still [don't have a proper APT repository](https://www.rstudio.com/products/rstudio/download-server/)...

Back to the present. What to do, what to do... I'm definitely against using the `deb` parameter directly. It requires upkeep when package versions change (does RStudio even provide old versions of the package?) and APT signing is a convenient security measure where the system can ensure that the package you requested is the correct one. And, this use case is deliberately not in the DebOps Software Source Policy.

If you want a good argument against handling specific package versions in the role, [check this out](https://github.com/debops-contrib/ansible-checkmk_server/pulls?utf8=%E2%9C%93&q=is%3Apr%20Update%20to%20version%20) (shoutout to @ganto for continued role support). It's a massive upkeep cost, dependent on the number of software releases and willingness of the maintainer to keep up. APT repositories were created for this reason, so why not use them? When I wrote `debops.rstudio_server`, at the time I hoped that its situation would change and RStudio would set up an APT repository at some point. Two Debian releases later, and here we are again. Therefore I urge you, to set up a local APT repository (see `debops.reprepro` role) and provide `rstudio-server` packages through it.

The role should be of course updated to handle new Debian releases. Since it's not active by default in the playbook, I think that failing hard if packages are not available might be a better option, perhaps with use of the `assert` Ansible module. Force shouldn't be used in production environments, which DebOps is focused on. If you cannot ensure that the packages install correctly on the current OS release, try an older one and bug the software author (RStudio) for an update.

**Comment by drybjed** [comment]
@evilham BTW, what do you want to do with `debops.rstudio_server` and DebOps in general? How does R fit in?

**Comment by evilham** [comment]
Ahà! Everything makes a lot of sense now :) thank you for explaining, it's quite enlightening.

I do find `rstudio_server` is an odd fit, which is why my first comment in the other issue was that I was nearly done implementing it myself, i.e., I hadn't even thought about searching for it in `debops`.

As for the present: Maybe if in the future enough people are interested, this could be reconsidered, but right now...  Maybe the pragmatic thing to do is to mark this package as `deprecated`? :-D It's not that difficult to do and given RStudio's packaging practices have a lot to improve (you already mentioned signing and repos)... It may not be worth the maintaining effort.

That's why, last week, I set up a server with a hacky playbook that used `apt:deb` to get the job done (and the server up). 

For completeness' sake: their RStudio Server package does not work out of the box with Debian Jessie, there is the issue I mentioned with `libssl`. Using the `force` flag to install does result in a working installation with Jessie but, as far as I remember, not with Stretch.
Also: they have these downloads servers: https://download2.rstudio.org/ for Rstudio Server and https://download3.rstudio.org/ for Shiny Server. Where they do keep old versions around, so having a hard coded link would not break awfully as long as they don't change anything.

In spite of that, I don't need that much convincing against supporting specific package versions, that's why instead of doing it, I decided to ask :). It's a problem waiting to happen.

As for your other comment/question: I maintain more servers than it's sane to do by hand, that's where ansible kicked in. Later when researching the pain points of ansible, I stumbled upon DebOps; which I eagerly welcomed.
That RStudio Server + Shiny Server I set up last week, is similar to your RStudio case: it's going to be a one-user thing where besides running those, I only need to backup their R scripts. I was mostly coming back to this from a "giving back" perspective.

So, what do you say? Package deprecation with a note encouraging DebOps users to show interest?

**Comment by drybjed** [comment]
Deprecating the role sounds like a good idea. Lately I thought about removing it from the `debops-playbooks` whenever my eyes stumbled on it somewhere, so maybe there's time for that.

Although, instead of doing it on the role level, I would look for some kind of procedure and status indicator for the whole project. If you haven't seen it yet, the DebOps project has [a status page](https://debops.org/status.html) with basic information about current role state. Perhaps another field there with some kind of status of each role could be useful. All of the data are scraped roughly hourly via a script and deployed using [an API](https://github.com/debops/debops-api/) ([deployment role](https://github.com/debops/ansible-debops_api/), [API endpoint](https://api.debops.org/)) written by @ypid. In the future I would see it changed from static set of HTML files to a more dynamic, perhaps Flask-based application, I just need to either find some time (busy with writing new roles and updating old ones at the moment) to write it, or find somebody to do it instead. In the end I would like to see something akin to [Debian Quality Assurance webpage](https://qa.debian.org/) which presents various statistics about the roles, their current state at a glance, etc.

For now, perhaps the current state of the role (maintained, deprecated, not sure about other states yet) could be set in the role `CHANGES.rst` file, similar to how maintainer is set there currently.

The role state changes should also be defined in the [DebOps Guidelines and Policies](https://docs.debops.org/en/latest/debops-policy/docs/index.html). In fact, I think that I might be doing it backwards - policy needs to be thought of and defined first, then it can be implemented. Time, time, time... Anyway, I suppose that this discussion would be better for the mailing list because I completely derailed the current issue. :-) I'll try to start a thread about DebOps Policy on the mailing list soon.

**Comment by evilham** [comment]
The API is done in python, which I'm fluent in :-), from a quick check, I'd think most of the code can be re-used for a dynamic API point and still keep the ability to generate static files.

In any case, I'd probably wait until this is discussed, decided and the guidelines are updated.

I'll now close this issue and the other one I had created + I'll add a new one to document the "pending deprecation".
